# Generated by Django 2.1 on 2020-06-24 11:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='titles',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_data',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 11, 15, 21, 245722, tzinfo=utc)),
        ),
    ]
